name: 'publish'

on:
  workflow_dispatch:

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add Kali repo
        run: |
          sudo sh -c "echo 'deb https://http.kali.org/kali kali-rolling main non-free contrib' > /etc/apt/sources.list.d/kali.list"
          wget -q -O - https://archive.kali.org/archive-key.asc | sudo apt-key add -
          sudo tee /etc/apt/preferences.d/kali.pref >/dev/null <<< "Package: *"
          sudo tee -a /etc/apt/preferences.d/kali.pref >/dev/null <<< "Pin: release a=kali-rolling"
          sudo tee -a /etc/apt/preferences.d/kali.pref >/dev/null <<< "Pin-Priority: 50"

          sudo apt-get update
          apt-cache policy
          sudo apt update
      - name: setup node
        uses: actions/setup-node@v4

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          sudo apt install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            libimobiledevice-glue-dev\
            libtatsu-dev\
            librsvg2-dev

      - name: install libimobiledevice
        run: |
          sudo apt-get install \
          	build-essential \
          	pkg-config \
          	checkinstall \
          	git \
          	autoconf \
          	automake \
          	libtool-bin \
          	libplist-dev \
          	libusbmuxd-dev \
          	libssl-dev \
          	usbmuxd

          git clone https://github.com/libimobiledevice/libimobiledevice.git
          cd libimobiledevice
          ./autogen.sh
          make
          sudo make install
          
            

      - name: install frontend dependencies
        run: |
          cd frontend
          npm install -g pnpm
          pnpm install
          cd ..

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
